<H3> Part I: Introduction to Pandas </H3>

Creating DataFrame and Series objects as well as reading data file

<I>all external datasets used in this notebook are sourced from [Kaggle](https://www.kaggle.com/code/residentmario/creating-reading-and-writing/data) <I>

In [22]:
import pandas as pd
pd.set_option('display.max_rows',5)
print("setup complete")

setup complete

Creating DataFrame 'fruits'

In [23]:
fruits = pd.DataFrame({'Apples':[30],'Bananas':[21]})
fruits

   Apples  Bananas
0      30       21

Creating DataFrame 'fruit_sales' with indexes

In [24]:
fruit_sales = pd.DataFrame({'Apples':[35,31],
                            'Bananas':[43,22]}, 
                            index=['2017sales','2018sales'])
fruit_sales

           Apples  Bananas
2017sales      35       43
2018sales      31       22

Creating a Series for ingredients

Flour     4 cups  <br>
Milk       1 cup<br>
Eggs     2 large<br>
Spam       1 can<br>
Name: Dinner, dtype: object

In [25]:
ingredients = pd.Series(['4 cups','1 cup','2 large','1 can'],
                        index=['Flour','Milk','Eggs','Spam'],
                        name='Dinner', dtype='object')
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

Reading the following csv dataset of wine reviews into a DataFrame called reviews

In [26]:
reviews = pd.read_csv("../Data/winemag-data_first150k.csv", index_col=0)

reviews
#learned df.shape and df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

Making a DF and saving it to disk as a csv file

In [27]:
animals = pd.DataFrame({'cows':[20,30],'goats':[21,25]},
                       index=['Year 1','Year 2'])
animals

        cows  goats
Year 1    20     21
Year 2    30     25

In [29]:
animals.to_csv("myData/cows_goats.csv", index=True)

check = pd.read_csv("myData/cows_goats.csv", index_col=0)
check.head()

        cows  goats
Year 1    20     21
Year 2    30     25