<H3> Part I: Creating, Reading and Writing </H3>

Creating DataFrame and Series objects as well as reading data file

<I>all external datasets used in this notebook are sourced from [Kaggle](https://www.kaggle.com/code/residentmario/creating-reading-and-writing/data) <I>

In [1]:
import pandas as pd
pd.set_option('display.max_rows',5)
print("setup complete")

setup complete

Creating DataFrame 'fruits'

In [2]:
fruits = pd.DataFrame({'Apples':[30],'Bananas':[21]})
fruits

   Apples  Bananas
0      30       21

Creating DataFrame 'fruit_sales' with indexes

In [3]:
fruit_sales = pd.DataFrame({'Apples':[35,31],
                            'Bananas':[43,22]}, 
                            index=['2017sales','2018sales'])
fruit_sales

           Apples  Bananas
2017sales      35       43
2018sales      31       22

Creating a Series for ingredients

Flour     4 cups  <br>
Milk       1 cup<br>
Eggs     2 large<br>
Spam       1 can<br>
Name: Dinner, dtype: object

In [4]:
ingredients = pd.Series(['4 cups','1 cup','2 large','1 can'],
                        index=['Flour','Milk','Eggs','Spam'],
                        name='Dinner', dtype='object')
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

Reading the following csv dataset of wine reviews into a DataFrame called reviews

In [5]:
reviews = pd.read_csv("../Data/winemag-data_first150k.csv", index_col=0)

reviews
#learned df.shape and df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

Making a DF and saving it to disk as a csv file

In [6]:
animals = pd.DataFrame({'cows':[20,30],'goats':[21,25]},
                       index=['Year 1','Year 2'])
animals

        cows  goats
Year 1    20     21
Year 2    30     25

In [7]:
animals.to_csv("myData/cows_goats.csv", index=True)

check = pd.read_csv("myData/cows_goats.csv", index_col=0)
check.head()

        cows  goats
Year 1    20     21
Year 2    30     25

<h3>Part II: Indexing, Selecting and Assigning</h3>
Selecting specific values of a pandas DataFrame or Series to work on/relevant data points

In [8]:
reviewsII = pd.read_csv("../Data/winemag-data-130k-v2.csv", index_col=0)
reviewsII.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Selecting the column "description" and assigning the value to "desc" variable

In [9]:
desc = reviewsII.description
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
                                ...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: str

Selecting the first value of "description"

In [10]:
f_desc = reviewsII.loc[0,'description']
f_desc

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

Selecting first row of data

In [11]:
f_row = reviewsII.iloc[0]
f_row

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

selecting first ten values form 'description' column

In [12]:
desc = reviewsII.loc[:9,'description']
desc

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
                           ...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, Length: 10, dtype: str

Select the records with index labels 1, 2, 3, 5, and 8

In [13]:
select_rec = reviewsII.iloc[[1,2,3,5,8]]
select_rec

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

Create a variable count containing the country, province, region_1, and region_2 columns of the records with the index labels 0, 1, 10, and 100

In [14]:
count = reviewsII.loc[[0,1,10,100],['country','province','region_1','region_2']]
count

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

Create a variable hundred containing the country and variety columns of the first 100 records.

In [15]:
hundred = reviewsII.loc[:99,['country','variety']]
#hundredI = reviewsII.iloc[:100,[0,11]]
#iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. loc, meanwhile, indexes inclusively.
hundred

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
..       ...                       ...
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

Create a DataFrame italian_wines containing reviews of wines made in Italy

In [16]:
italian_wines = reviewsII.loc[reviewsII.country == 'Italy']
italian_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

Create a DataFrame top_oceania_wines containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [17]:
top_oceania_wines = reviewsII.loc[(reviewsII.points >=95) 
                                  & (reviewsII.country.isin(['Australia','New Zealand']))]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck

<h3>Part III: Summary Functions and Maps</h3>
Re-formatting data to get the input according to the standards

Mean and Median of 'points' column

In [18]:
mean = reviewsII.points.mean()
median = reviewsII.points.median()
median

np.float64(88.0)

In [19]:
mean

np.float64(88.44713820775404)

countries in dataset list

In [20]:
countries = reviewsII.country.unique()
countries

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                      nan,                 'Turkey',         'Czech Republic',
               'Slovenia',             'Luxembourg',                'Croatia',
                'Georgia',                'Uruguay',                'England',
                'Lebanon',                 'Serbia',                 'Brazil',
                'Moldova',                'Morocco',                   'Peru',
                  'India',               'Bulgaria',                 'Cyprus',
                'Armenia',            'Switzerland', 'Bosnia and Herzegovina',
                'Ukraine',               'Slovakia',              'Macedonia',
                  'China',                  'Egypt']
Length: 44, dtype: str

How often each country appears

In [21]:
countries_count = reviewsII.country.value_counts()
countries_count

country
US        54504
France    22093
          ...
China         1
Egypt         1
Name: count, Length: 43, dtype: int64

Create variable centered_price containing a version of the price column with the mean price subtracted

In [22]:
mean_price = reviewsII.price.mean()
centered_price = reviewsII.price - mean_price
centered_price

0               NaN
1        -20.363389
            ...
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [23]:
#alternative method using map() 
review_price_mean = reviewsII.price.mean()
centered_price2 = reviewsII.price.map(lambda p: p - review_price_mean)
centered_price2

0               NaN
1        -20.363389
            ...
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

In [26]:
bargain_wine = reviewsII.loc[(reviewsII.points/reviewsII.price).idxmax(), 'title']
bargain_wine

'Bandit NV Merlot (California)'

Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

In [28]:
tropical_count = reviewsII.description.map(lambda b: "tropical" in b).sum()
fruity_count = reviewsII.description.map(lambda b: "fruity" in b).sum()

descriptor_count = pd.Series([tropical_count,fruity_count], index = ['tropical','fruity'], name = 'countor')
descriptor_count

tropical    3607
fruity      9090
Name: countor, dtype: int64

We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [36]:
def stars(row):
    if row.country == "Canada":
        return 3
    elif row.points>=95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

star_ratings = reviewsII.apply(stars, axis=1)
star_ratings

0         2
1         2
         ..
129969    2
129970    2
Length: 129971, dtype: int64

<h3>Part IV: Grouping and Sorting</h3>

In [39]:

#Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, 
#and whose values count how many reviews each person wrote.

taster_count = reviewsII.groupby('taster_twitter_handle').taster_twitter_handle.count()
taster_count

taster_twitter_handle
@AnneInVino        3685
@JoeCz             5147
                   ...
@winewchristina       6
@worldwineguys     1005
Name: taster_twitter_handle, Length: 15, dtype: int64

In [41]:
# Create a Series whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that 4.0 dollars is at the top and 3300.0 dollars is at the bottom).
points = reviewsII.groupby('price')['points'].max().sort_index()
points

price
4.0       86
5.0       87
          ..
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [43]:
#What are the minimum and maximum prices for each variety of wine? Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.
min_max = reviewsII.groupby('variety').price.agg([min,max])
min_max

              min   max
variety
Abouriou     15.0  75.0
Agiorgitiko  10.0  66.0
...           ...   ...
Çalkarası    19.0  19.0
Žilavka      15.0  15.0

[707 rows x 2 columns]

In [58]:
#What are the most expensive wine varieties? Create a variable sorted_varieties containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).
exp_wine = min_max.sort_values(by = ['min','max'], ascending = False)

exp_wine.head()

                    min    max
variety
Ramisco           495.0  495.0
Terrantez         236.0  236.0
Francisa          160.0  160.0
Rosenmuskateller  150.0  150.0
Tinta Negra Mole  112.0  112.0

In [60]:
#Create a Series whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the taster_name and points columns.
reviewers_mean_rating = reviewsII.groupby('taster_name').points.mean()
reviewers_mean_rating

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
                        ...
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, Length: 19, dtype: float64

In [61]:
#to see summary of the range of values from above
reviewers_mean_rating.describe()

count    19.000000
mean     88.233026
           ...
75%      88.975256
max      90.562551
Name: points, Length: 8, dtype: float64

In [63]:
#What combination of countries and varieties are most common? Create a Series whose index is a MultiIndexof {country, variety} pairs.
#For example, a pinot noir produced in the US should map to {"US", "Pinot Noir"}. Sort the values in the Series in descending order 
#based on wine count.

countries_varieties = reviewsII.groupby(['country','variety']).size().sort_values(ascending=False)
countries_varieties

country  variety
US       Pinot Noir            9885
         Cabernet Sauvignon    7315
                               ...
Italy    Catalanesca              1
         Carmenère                1
Length: 1612, dtype: int64

<h3>Part V: Data Types and Missing Values</h3>

In [65]:
#to see datatype of a column

dtype = reviewsII.points.dtype
dtype

dtype('int64')

In [67]:
#Create a Series from entries in the points column, but convert the entries to strings

int64_to_str = reviewsII.points.astype(str)
int64_to_str

0         87
1         87
          ..
129969    90
129970    90
Name: points, Length: 129971, dtype: str

In [75]:
#check how many values are null in a column

missing_values = reviewsII[pd.isnull(reviewsII.price)]
total_missing = len(missing_values)

total_missing

#total_missing = reviewsII.price.isnull().sum()  //This can also be used//

8996

In [78]:
#Create a Series counting the number of times each value occurs in the region_1 field. 
# This field is often missing data, so replace missing values with Unknown. Sort in descending order.

reviews_per_region = reviewsII.region_1.fillna("Unknown").value_counts()

reviews_per_region

region_1
Unknown                21247
Napa Valley             4480
                       ...
Bardolino Superiore        1
Paestum                    1
Name: count, Length: 1230, dtype: int64